---
title: "Getting started"
format:
  html:
    toc: true
    theme: 
      light: flatly
      dark: darkly
    html-math-method: katex
    number-sections: true
    anchor-sections: true
    code-tools: true
    code-copy: true
    code-link: true
    code-fold: true
    code-summary: "Show the code"
comments:
  giscus: 
    repo: luckinet/clueRIO
highlight-style: github
fontsize: 12pt
linestretch: 1.15
urlcolor: blue
vignette: >
  %\VignetteIndexEntry{getting_started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(clueRIO)
```


# Installation

Install the official version from CRAN:

```{r, eval=FALSE}
# install.packages("clueRIO")
```

Install the latest development version from github:

```{r, eval=FALSE}
devtools::install_github("luckinet/clueRIO")
```


# Examples

```{r, eval=FALSE}
library(clueRIO); library(tibble)

data <- system.file("test_data", package = "clueRIO", mustWork = TRUE)

# our example model will be called '2 land systems (ls2), 1 demand (d1)'.
model <- "ls2d1"

# open a new scene for the model
minimal <- clue_scene(
  root = paste0(tempdir(), "/", model), 
  name = model, 
  period = c(2000, 2024),
  regions = paste0(data, "/test_region.gpkg"),
  description = "this is a minimal showcase where forest is converted to cropland to produce crops.")

# first, specify the gridded items ...
# ... initial land systems
minimal <- minimal |> 
  clue_gridded(file = paste0(data, "/ls2.tif"),
               type = "initial")

# ... then suitability drivers
minimal <- minimal |> 
  clue_gridded(file = paste0(data, "/suitability1.tif"), 
               type = "driver", name = "cropland_suit") |> 
  clue_gridded(file = paste0(data, "/suitability2_0.tif"),
               type = "driver", name = "forest_suit")

# setup land types
minimal <- minimal |> 
  # forest shall be convertable to cropland
  clue_landtype(name = "forest", resistance = 0.5,
                suitability = tibble(driver = c("const", "forest_suit"),
                                     beta = c(1, 1)),
                conversion = tibble(to = "cropland", 
                                    label = "intensification")) |> 
  # cropland shall produce crops
  clue_landtype(name = "cropland", resistance = 0.5,
                suitability = tibble(driver = c("const", "cropland_suit"),
                                     beta = c(1, 1)),
                production = tibble(name = "crops", 
                                    amount = 1, priority = 1))


# setup goods and services
minimal <- minimal |> 
  clue_goods(name = "crops", 
             demand = tibble(year = c(2000:2024), 
                             region = "ravenholm", 
                             amount = seq(from = 4760, to = 5000, length.out = 25)))

# possibly adapt options
# clue_options(...)

# initiate the model
clue_initiate(scene = minimal)

# and finally run the model
clue_run(scene = minimal)

# possibly backup the model outputs
# clue_backup(scene = minimal)
```
